version: '3.3'

services:
  mysql:
    image: mariadb:latest
    container_name: hw_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build:
      context: ./
    container_name: hw_web
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./code:/var/www/html
    depends_on:
      - mysql
    command: /usr/local/bin/wait-for-it.sh mysql:3306 -- /bin/bash -c "/usr/local/bin/wp-setup.sh && apache2-foreground"

volumes:
  mysql-data:

networks:
  hw-network: